### ISSUE TITLE
incanter require statements in dp-examples.clj, but incanter is not a proj. dependency

### ISSUE THREAD

**Issue by skynx** [michaellindon/distributions#1]
Is the file `dp-examples.clj` just an example REPL session? I see that it shares some content with the Dirichlet processes page in `docs/`, which makes sense, but I can't figure out why it's in `src/`. There is a require [statement](https://github.com/michaellindon/distributions/blob/875cb937c587e5d5cd554411a8f5298d48edac4d/src/distributions/dp-examples.clj#L8-L9) in there for incanter/incanter.core and incanter/incanter.charts.

Incanter isn't stated as a dependency in the project file, which caused some "could not locate" errors for me at first, which can be fixed by declaring a dependency in the project using distributions; however, that's not ideal, and since `dp-examples.clj` seems to have an illustrative purpose I think it might make sense to avoid distributing it.

**Comment by michaellindon** [comment]
Thanks for opening up this issue. You're absolutely correct, it was bad book-keeping on my part. I've moved dp-examples.clj from src to docs. I've deployed a new version to clojars and updated the github repo :) Thanks for brining this to my attention!

**Comment by skynx** [comment]
Thanks! Looks like everything was resolved in the 0.1.3-SNAPSHOT.
